// Code generated by protoc-gen-go. DO NOT EDIT.
// source: knnservice.proto

/*
Package knnservice is a generated protocol buffer package.

It is generated from these files:
	knnservice.proto

It has these top-level messages:
	KnnRequest
	Feature
	KnnResponse
	InsertionRequest
	InsertionResponse
*/
package knnservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request message for creating a new customer
type KnnRequest struct {
	Id        int32     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Timestamp int64     `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Timeout   int64     `protobuf:"varint,3,opt,name=timeout" json:"timeout,omitempty"`
	K         int32     `protobuf:"varint,4,opt,name=k" json:"k,omitempty"`
	Feature   []float64 `protobuf:"fixed64,5,rep,packed,name=feature" json:"feature,omitempty"`
}

func (m *KnnRequest) Reset()                    { *m = KnnRequest{} }
func (m *KnnRequest) String() string            { return proto.CompactTextString(m) }
func (*KnnRequest) ProtoMessage()               {}
func (*KnnRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KnnRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KnnRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *KnnRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *KnnRequest) GetK() int32 {
	if m != nil {
		return m.K
	}
	return 0
}

func (m *KnnRequest) GetFeature() []float64 {
	if m != nil {
		return m.Feature
	}
	return nil
}

type Feature struct {
	Feature   []float64 `protobuf:"fixed64,1,rep,packed,name=feature" json:"feature,omitempty"`
	Timestamp int64     `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Label     string    `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Feature) GetFeature() []float64 {
	if m != nil {
		return m.Feature
	}
	return nil
}

func (m *Feature) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Feature) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type KnnResponse struct {
	Id       int32      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Features []*Feature `protobuf:"bytes,2,rep,name=features" json:"features,omitempty"`
}

func (m *KnnResponse) Reset()                    { *m = KnnResponse{} }
func (m *KnnResponse) String() string            { return proto.CompactTextString(m) }
func (*KnnResponse) ProtoMessage()               {}
func (*KnnResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *KnnResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KnnResponse) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

type InsertionRequest struct {
	Id        int32     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Timestamp int64     `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Label     string    `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
	Feature   []float64 `protobuf:"fixed64,4,rep,packed,name=feature" json:"feature,omitempty"`
}

func (m *InsertionRequest) Reset()                    { *m = InsertionRequest{} }
func (m *InsertionRequest) String() string            { return proto.CompactTextString(m) }
func (*InsertionRequest) ProtoMessage()               {}
func (*InsertionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InsertionRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertionRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *InsertionRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *InsertionRequest) GetFeature() []float64 {
	if m != nil {
		return m.Feature
	}
	return nil
}

type InsertionResponse struct {
	Id   int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Code int32 `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
}

func (m *InsertionResponse) Reset()                    { *m = InsertionResponse{} }
func (m *InsertionResponse) String() string            { return proto.CompactTextString(m) }
func (*InsertionResponse) ProtoMessage()               {}
func (*InsertionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InsertionResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertionResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*KnnRequest)(nil), "knnservice.KnnRequest")
	proto.RegisterType((*Feature)(nil), "knnservice.Feature")
	proto.RegisterType((*KnnResponse)(nil), "knnservice.KnnResponse")
	proto.RegisterType((*InsertionRequest)(nil), "knnservice.InsertionRequest")
	proto.RegisterType((*InsertionResponse)(nil), "knnservice.InsertionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KnnService service

type KnnServiceClient interface {
	// Get all Customers with filter - A server-to-client streaming RPC.
	// rpc GetCustomers(CustomerFilter) returns (stream CustomerRequest) {}
	// Create a new Customer - A simple RPC
	GetKnn(ctx context.Context, in *KnnRequest, opts ...grpc.CallOption) (*KnnResponse, error)
	Insert(ctx context.Context, in *InsertionRequest, opts ...grpc.CallOption) (*InsertionResponse, error)
}

type knnServiceClient struct {
	cc *grpc.ClientConn
}

func NewKnnServiceClient(cc *grpc.ClientConn) KnnServiceClient {
	return &knnServiceClient{cc}
}

func (c *knnServiceClient) GetKnn(ctx context.Context, in *KnnRequest, opts ...grpc.CallOption) (*KnnResponse, error) {
	out := new(KnnResponse)
	err := grpc.Invoke(ctx, "/knnservice.KnnService/GetKnn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knnServiceClient) Insert(ctx context.Context, in *InsertionRequest, opts ...grpc.CallOption) (*InsertionResponse, error) {
	out := new(InsertionResponse)
	err := grpc.Invoke(ctx, "/knnservice.KnnService/Insert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KnnService service

type KnnServiceServer interface {
	// Get all Customers with filter - A server-to-client streaming RPC.
	// rpc GetCustomers(CustomerFilter) returns (stream CustomerRequest) {}
	// Create a new Customer - A simple RPC
	GetKnn(context.Context, *KnnRequest) (*KnnResponse, error)
	Insert(context.Context, *InsertionRequest) (*InsertionResponse, error)
}

func RegisterKnnServiceServer(s *grpc.Server, srv KnnServiceServer) {
	s.RegisterService(&_KnnService_serviceDesc, srv)
}

func _KnnService_GetKnn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnnServiceServer).GetKnn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knnservice.KnnService/GetKnn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnnServiceServer).GetKnn(ctx, req.(*KnnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnnService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnnServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knnservice.KnnService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnnServiceServer).Insert(ctx, req.(*InsertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KnnService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "knnservice.KnnService",
	HandlerType: (*KnnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKnn",
			Handler:    _KnnService_GetKnn_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _KnnService_Insert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knnservice.proto",
}

func init() { proto.RegisterFile("knnservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0xc5, 0x49, 0x93, 0xd2, 0x2b, 0x42, 0xc5, 0x20, 0xb0, 0xaa, 0x22, 0x45, 0x99, 0x32, 0x15,
	0xa9, 0x0c, 0x0c, 0xec, 0x54, 0xa8, 0x12, 0x83, 0x19, 0x98, 0xd3, 0xe6, 0x90, 0xa2, 0xb4, 0x76,
	0x88, 0x1d, 0x26, 0xbe, 0x82, 0x2f, 0x46, 0xb1, 0x1b, 0xe2, 0x52, 0x2a, 0x24, 0x36, 0xbf, 0xbb,
	0xa7, 0xbb, 0xf7, 0xde, 0x19, 0x46, 0x85, 0x10, 0x0a, 0xab, 0xf7, 0x7c, 0x85, 0xd3, 0xb2, 0x92,
	0x5a, 0x52, 0xe8, 0x2a, 0xf1, 0x07, 0xc0, 0x42, 0x08, 0x8e, 0x6f, 0x35, 0x2a, 0x4d, 0x4f, 0xc1,
	0xcb, 0x33, 0x46, 0x22, 0x92, 0x04, 0xdc, 0xcb, 0x33, 0x3a, 0x81, 0x81, 0xce, 0x37, 0xa8, 0x74,
	0xba, 0x29, 0x99, 0x17, 0x91, 0xc4, 0xe7, 0x5d, 0x81, 0x32, 0xe8, 0x37, 0x40, 0xd6, 0x9a, 0xf9,
	0xa6, 0xd7, 0x42, 0x7a, 0x02, 0xa4, 0x60, 0x3d, 0x33, 0x86, 0x14, 0x0d, 0xef, 0x15, 0x53, 0x5d,
	0x57, 0xc8, 0x82, 0xc8, 0x4f, 0x08, 0x6f, 0x61, 0xfc, 0x02, 0xfd, 0x07, 0xfb, 0x74, 0x49, 0x64,
	0x87, 0xf4, 0x87, 0x88, 0x0b, 0x08, 0xd6, 0xe9, 0x12, 0xd7, 0x46, 0xc2, 0x80, 0x5b, 0x10, 0x3f,
	0xc1, 0xd0, 0xd8, 0x52, 0xa5, 0x14, 0x0a, 0xf7, 0x7c, 0xdd, 0xc0, 0xf1, 0x76, 0xba, 0x62, 0x5e,
	0xe4, 0x27, 0xc3, 0xd9, 0xf9, 0xd4, 0x89, 0x69, 0xab, 0x89, 0x7f, 0x93, 0xe2, 0x12, 0x46, 0x8f,
	0x4d, 0x5b, 0xe7, 0xf2, 0x9f, 0x61, 0xfd, 0xaa, 0xd3, 0x75, 0xdd, 0xdb, 0x8d, 0xe6, 0x0e, 0xce,
	0x9c, 0x8d, 0x07, 0x7c, 0x50, 0xe8, 0xad, 0x64, 0x86, 0x66, 0x5b, 0xc0, 0xcd, 0x7b, 0xf6, 0x49,
	0xcc, 0x49, 0x9f, 0xad, 0x17, 0x7a, 0x0f, 0xe1, 0x1c, 0xf5, 0x42, 0x08, 0x7a, 0xe9, 0x5a, 0xec,
	0x8e, 0x3e, 0xbe, 0xda, 0xab, 0xdb, 0x6d, 0xf1, 0x11, 0x9d, 0x43, 0x68, 0x45, 0xd0, 0x89, 0x4b,
	0xfa, 0x19, 0xc5, 0xf8, 0xfa, 0x40, 0xb7, 0x1d, 0xb4, 0x0c, 0xcd, 0xcf, 0xbb, 0xfd, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0xa0, 0x3c, 0x2d, 0x1c, 0x8d, 0x02, 0x00, 0x00,
}
